# Generated by Django 4.0 on 2022-01-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mysite', '0002_exptransactions_extra_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='expaccounts',
            name='user_acc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
